Feature/modal
KNU-Develop/todayscrum-frontend pull request #10
Opened 2024-08-03 08:00 UTC by seowooda

# PR Type

- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 패키지 의존성 변경, CI/CD, 환경 설정 등

# Overview

- 일정 관리 모달창 디자인 수정
- 참가자 기능 추가

- todo
- API 연결
- 코드 정리

# Additional Comment

팀 일정일 때 버튼이 기능을 하지 않습니다 이 부분은 추후에 수정하겠습니다

# Issue

#XXX

# Check List

- [x] 관련된 이슈를 연결하였나요?
- [x] 올바른 PR 컨벤션을 작성했나요?
- [x] 적절한 라벨을 선택했나요?
- [x] Assignee와 Reviewer를 설정했나요?

2024-08-03 15:53 UTC, hin6150 requested changes

2024-08-03 15:53 UTC, hin6150 commented on src/components/Modal/ScheduleModal.tsx
> +            )}
[P3] 추후 API 연동을 고려하면 생성과 수정 모달은 분리하는게 좋아보입니다.

2024-08-03 15:53 UTC, hin6150 commented on src/components/Modal/ScheduleModal.tsx
>                    </label>
[P2] 하루종일을 체크했음에도 일정 시간이 포함된 형태의 Input Box를 표기하는 오류

2024-08-03 15:53 UTC, hin6150 commented on src/components/Modal/ScheduleModal.tsx
>              </div>
[P2] 맞춤 반복 설정을 했음에도, 해당 내용이 표기되지 않는 오류

2024-08-03 15:53 UTC, hin6150 commented on src/components/Modal/ScheduleModal.tsx
>              </div>
[P2] 반복 종료 일자가 일정 날짜 이전으로 설정 가능한 오류

2024-08-03 15:53 UTC, hin6150 commented on src/components/InputForm/InputForm.tsx
>            </FormControl>
[P2] 이메일의 경우 팀원 추가가 불가능한 오류

2024-08-03 15:53 UTC, hin6150 commented on src/components/Modal/ScheduleModal.tsx
>              </div>
[P2] 매년 m월 n일과 같은 반복 옵션이 위의 일정 시간과 연동되지 않는 오류

2024-08-03 15:53 UTC, hin6150 commented on src/components/InputForm/InputForm.tsx
> +                        ? formatDate(new Date(field.value), startDate, endDate)
[P2] 일정 시간이 종료 시간이 시작 시간보다 빠른 오류

2024-08-05 08:11 UTC, seowooda commented on src/components/Modal/ScheduleModal.tsx
>              </div>
> [P2] 맞춤 반복 설정을 했음에도, 해당 내용이 표기되지 않는 오류

현재 이 부분이 잘 안됩니다..ㅠㅠ

2024-08-05 08:18 UTC, seowooda commented on src/components/Modal/ScheduleModal.tsx
>              </div>
> [P2] 매년 m월 n일과 같은 반복 옵션이 위의 일정 시간과 연동되지 않는 오류

이건 수정했는데 
일정 시간을 2024.08.05 (월)로 선택하고 반복 여부를 매주 월요일을 선택했을 때 일정 시간을 다른 요일인 날짜로 바꾸면 반복 여부가 제대로 반영되지 않는 오류가 발생합니다. 
해당 부분을 날짜를 바꿨을 때 원래의 선택을 유지하면서 아이템의 이름이 선택된 일정 시간으로 바뀌는 것이 아닌 [반복 안함]으로 선택되게 할까하는데 어떤게 더 나을까요?

2024-08-05 19:57 UTC, hin6150 commented on src/components/Modal/ScheduleModal.tsx
>              </div>
> > [P2] 매년 m월 n일과 같은 반복 옵션이 위의 일정 시간과 연동되지 않는 오류
> 
> 이건 수정했는데 일정 시간을 2024.08.05 (월)로 선택하고 반복 여부를 매주 월요일을 선택했을 때 일정 시간을 다른 요일인 날짜로 바꾸면 반복 여부가 제대로 반영되지 않는 오류가 발생합니다. 해당 부분을 날짜를 바꿨을 때 원래의 선택을 유지하면서 아이템의 이름이 선택된 일정 시간으로 바뀌는 것이 아닌 [반복 안함]으로 선택되게 할까하는데 어떤게 더 나을까요?

네 일단 하실 수 있는 방식으로 구현해주세요

2024-08-05 19:58 UTC, hin6150 commented on src/components/Modal/ScheduleModal.tsx
>              </div>
> > [P2] 맞춤 반복 설정을 했음에도, 해당 내용이 표기되지 않는 오류
> 
> 현재 이 부분이 잘 안됩니다..ㅠㅠ

마찬가지로 진행 가능한 부분까지만 해서 작업해주세요

2024-08-07 14:16 UTC, merged